### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by raulanatol** [rogercampa/cursogit#8]
https://github.com/raulanatol/curso_git_ull_2016/wiki/Reglas-para-puntuar

**Comment by simonemarin** [comment]
hola el punto numero 1 se refiere a un compañero de mi propio equipo?

**Comment by raulanatol** [comment]
Sí @simonemarin. Pero no vale dártelo a ti mismo :smile:

**Comment by ardielgr** [comment]
:+1: Mejor anuario

**Comment by moiseslodeiro** [comment]
:+1: Más original

**Comment by moiseslodeiro** [comment]
:+1: Mejor anuario

**Comment by franmorales86** [comment]
:+1: Mejor anuario

**Comment by jurses** [comment]
:+1: @simonemarin

**Comment by yodra** [comment]
:+1: Mejor anuario

**Comment by infojuani** [comment]
:+1: Mejor anuario

**Comment by simonemarin** [comment]
:+1: @jurses

**Comment by Dacoher** [comment]
:+1: Más original
